steps:
  # Only needed for local dev / custom images.
  - id: experimental-pull-images
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker pull gcr.io/$PROJECT_ID/firebase-app-hosting-22/build 
      docker tag gcr.io/$PROJECT_ID/firebase-app-hosting-22/build gcr.io/buildpacks/firebase-app-hosting-22/build
      docker pull gcr.io/$PROJECT_ID/firebase-app-hosting-22/run
      docker tag gcr.io/$PROJECT_ID/firebase-app-hosting-22/run gcr.io/buildpacks/firebase-app-hosting-22/run
  - id: build-from-source
    name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
    - build
    - $LOCATION-docker.pkg.dev/$PROJECT_ID/firestack-images/app-image:$COMMIT_SHA
    - --builder
    # - gcr.io/buildpacks/google-22/builder:latest
    # - gcr.io/buildpacks/firebase-app-hosting-22/builder@sha256:52abc404bbca0c38f3dcd36e8c855cd0ee7cc55ef0253091544c19e4eb260389
    - gcr.io/$PROJECT_ID/firebase-app-hosting-22/builder:latest
  - id: finalize-build
    name: gcr.io/$PROJECT_ID/firebase-app-hosting-22/builder:latest
    entrypoint: /bin/publisher

images:
  - $LOCATION-docker.pkg.dev/$PROJECT_ID/firestack-images/app-image:$COMMIT_SHA

